// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYbCYStOHaAJhENdm9RxdXCeiOrB6sWFM',
    appId: '1:215098544594:web:d5219bbba1766bc888f80b',
    messagingSenderId: '215098544594',
    projectId: 'alumate-c8f9f',
    authDomain: 'alumate-c8f9f.firebaseapp.com',
    storageBucket: 'alumate-c8f9f.firebasestorage.app',
    measurementId: 'G-Q4T8TGDX9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNgW6zNYJq6jU8hC5BZJTssWG7PQXGAQk',
    appId: '1:215098544594:android:4bbef89ac5acfe4288f80b',
    messagingSenderId: '215098544594',
    projectId: 'alumate-c8f9f',
    storageBucket: 'alumate-c8f9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_y0NzmVByjZiRzEg8xAIz5jBSloxaZr0',
    appId: '1:215098544594:ios:05823624274dbdb988f80b',
    messagingSenderId: '215098544594',
    projectId: 'alumate-c8f9f',
    storageBucket: 'alumate-c8f9f.firebasestorage.app',
    iosBundleId: 'com.example.frontedPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_y0NzmVByjZiRzEg8xAIz5jBSloxaZr0',
    appId: '1:215098544594:ios:05823624274dbdb988f80b',
    messagingSenderId: '215098544594',
    projectId: 'alumate-c8f9f',
    storageBucket: 'alumate-c8f9f.firebasestorage.app',
    iosBundleId: 'com.example.frontedPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYbCYStOHaAJhENdm9RxdXCeiOrB6sWFM',
    appId: '1:215098544594:web:49a8a48289837aa388f80b',
    messagingSenderId: '215098544594',
    projectId: 'alumate-c8f9f',
    authDomain: 'alumate-c8f9f.firebaseapp.com',
    storageBucket: 'alumate-c8f9f.firebasestorage.app',
    measurementId: 'G-8YVR0BRL42',
  );
}
